# ECM1416: Computational Mathematics
## Worksheet #2: Matrix inverse


In [1]:
# import the numpy package in the np namespace
import numpy as np

# this line will load the plotting function into the namespace plt.
import matplotlib.pyplot as plt

# the following lines prevent Python from opening new windows for figures. 
%matplotlib inline

### Linear algebra functions in numpy
Many linear algebra functions in Numpy are stored in the <tt>numpy.linalg</tt> namespace: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

For example, the determinant of a matrix can be calculated using <tt>numpy.linalg.det()</tt>, and the inverse using <tt>numpy.linalg.inv()</tt>

## Exercises
### Exercise 1: Determinant
The aim of this exercise is to code a function implementing the Laplace formula for calculating the determinant. You are recommended to use subfunctions for calculating the minors and cofactors (you will need them later). 
Compare your function to Numpy's determinant function on a couple of matrices. 


In [2]:
def findMinor(A, row, colummn):
    """Returns the minor of a matrix A at a given row and column."""
    A = np.delete(A, row, 0) # Deletes row at index 'row'
    A = np.delete(A, colummn, 1) # Deletes column at index 'column'
    return A

In [3]:
#Testing the findMinor function
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Creates a 3x3 matrix
print(findMinor(A, 0, 0)) # Should return [[5,6],[8,9]]

[[5 6]
 [8 9]]


In [4]:
def determinant2x2(A):
    """Returns the determinant of a 2x2 matrix."""
    return A[0][0]*A[1][1] - A[0][1]*A[1][0] # ad - bc

In [5]:
#Testing the determinant2x2 function
A = np.array([[1,2],[3,4]]) # Creates a 2x2 matrix
print(determinant2x2(A)) # Should return -2

-2


In [6]:
def findCofactor(A, row, column):
    """Returns the cofactor of a matrix A at a given row and column."""
    A = findMinor(A, row, column) # Finds the minor of A at the given row and column
    determinantA = determinant2x2(A) # Finds the determinant of the minor
    cofactor = (-1)**(row+column) * determinantA
    return cofactor

In [7]:
#Testing the findCofactor function
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Creates a 3x3 matrix
print(findCofactor(A, 0, 0)) # Should return -3

-3


In [8]:
def determinant3x3(A):
    """Returns the determinant of a 3x3 matrix A."""
    determinantA = 0
    for i in range (0,3):
        # r0c0*cofactor(r0c0) + r0c1*cofactor(r0c1) + r0c2*cofactor(r0c2)
        determinantA += A[0][i]*findCofactor(A, 0, i)

    return determinantA

In [9]:
#Testing the determinant3x3 function
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Creates a 3x3 matrix
print(determinant3x3(A)) # Should return 0

0


### Exercise 2: Inverse
Build on the code you wrote for part one to provide the Cramer's rule solution to calculate the inverse of a matrix (as discussed in the lecture). Again compare your approach to numpy's results on some matrices. 

In [10]:
def inverse2x2(A):
    '''Returns the inverse of a 2x2 matrix A.'''
    determinantA = determinant2x2(A) # Finds the determinant of A
    if determinantA == 0:
        return "Matrix is not invertible"
    adjugateA = np.array([[A[1][1], -A[0][1]], [-A[1][0], A[0][0]]]) # Creates the [[d -b], [-c a]] matrix (the adjugate of A)
    inverse = 1/determinantA * adjugateA # 1/det(A) * adj(A)
    return inverse

In [11]:
#Testing the inverse2x2 function
A = np.array([[1,2],[3,4]]) # Creates a 2x2 matrix
print(inverse2x2(A)) # Should return [[-2,1],[1.5,-0.5]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [12]:
#Testing the inverse2x2 function with a non-invertible matrix
A = np.array([[1,2],[2,4]]) # Creates a 2x2 matrix
print(inverse2x2(A)) # Should return "Matrix is not invertible"

Matrix is not invertible


In [13]:
def inverse3x3(A):
    '''Returns the inverse of a 3x3 matrix A.'''
    determinantA = determinant3x3(A) # Finds the determinant of A
    if determinantA == 0:
        return "The matrix is not invertible." # If the determinant is 0, the matrix is not invertible
    adjugateA = np.array([[findCofactor(A, 0, 0), findCofactor(A, 0, 1), findCofactor(A, 0, 2)], [findCofactor(A, 1, 0), findCofactor(A, 1, 1), findCofactor(A, 1, 2)], [findCofactor(A, 2, 0), findCofactor(A, 2, 1), findCofactor(A, 2, 2)]]) # Creates the [[d -b], [-c a]] matrix (the adjugate of A)
    inverse = 1/determinantA * adjugateA # 1/det(A) * adj(A)
    return inverse

In [14]:
#Testing the inverse3x3 function
A = np.array([[9,1,2],[5,2,7],[4,6,3]]) # Creates a 3x3 matrix
print(inverse3x3(A)) 

[[ 0.13483146 -0.04868914 -0.082397  ]
 [-0.03370787 -0.07116105  0.18726592]
 [-0.01123596  0.19850187 -0.04868914]]


In [15]:
#Testing the inverse3x3 function
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Creates a 3x3 matrix
print(inverse3x3(A)) # Should return "The matrix is not invertible."

The matrix is not invertible.


### Exercise 3: System of linear equations
The aim of this exercise is to use the inverse to solve a system of linear equations. To this end, let's look at a small problem: 
1. On Monday, you went to the shop and bought 2 coffees, one tea and 5 donuts (generous of you) and paid 12 pounds. 
2. On Tuesday, you went again and bought 3 coffees and 6 donuts and pay 13.50. 
3. Finally on Wednesday, you bought 1 coffee, 1 tea and two donuts and pay 6.50. 

Question: what is the price of each of the items you bought this week? 

Model this as a system of linear equation and solve it using the inverse. 

In [16]:
#If x = coffee, y = tea and z = doughnuts:
#1. 2x + y + 5z = 12.00
#2. 3x + 6z = 13.50
#3. x + y + 2z = 6.50

#The above equations can be written as a matrix equation:
#A * xyz = b

# Therefore, ...
A = np.array([[2,1,5],[3,0,6],[1,1,2]])
b = np.array([[12.00],[13.50],[6.50]])

inverseA = inverse3x3(A)
transposeA = inverseA.T

xyz = np.dot(transposeA, b) # Use np.dot() to perform matrix multiplication

print("coffee = " + str(xyz[0][0]))
print("tea = " + str(xyz[1][0]))
print("doughnuts = " + str(xyz[2][0]))


coffee = 2.5
tea = 2.0
doughnuts = 1.0
